home page and logistration pages changes
Ali-D-Akbar/react-redux-blog-app-frontend pull request #7
Opened 2019-09-30 13:21 UTC by Ali-D-Akbar

# Blog App Frontend:
Description: Home Page and Logistration pages are now changed as per the requirements. Most importantly, a Sticky Footer and Default Image has been added.
Installation Instructions:

1. run `npm install`
2. run npm start

![Screenshot from 2019-09-30 17-24-41](https://user-images.githubusercontent.com/52413434/65882728-05f16980-e3af-11e9-97e2-f73a02c16fd8.png)
![Screenshot from 2019-09-30 17-24-57](https://user-images.githubusercontent.com/52413434/65882730-05f16980-e3af-11e9-94a6-e434234fb39f.png)
![Screenshot from 2019-09-30 18-09-49](https://user-images.githubusercontent.com/52413434/65882732-05f16980-e3af-11e9-99eb-3ecdd59e8d4b.png)

2019-10-03 13:27 UTC, zubair-arbi requested changes

2019-10-03 13:27 UTC, zubair-arbi commented on src/components/accounts/Register.js
> +                            <label>Username*</label>
make these required fields accessible.

2019-10-03 13:38 UTC, Ali-D-Akbar commented on src/components/accounts/Register.js
> +                            <label>Username*</label>
Done.

2019-10-07 10:47 UTC, zubair-arbi approved these changes
👍

2019-10-07 10:47 UTC, zubair-arbi commented
Remember to squash the commits before merge.

2019-10-07 10:58 UTC, merged